// Pines por defecto para AI-THINKER ESP32-CAM
#define Y2_GPIO_NUM  5
#define Y3_GPIO_NUM  18
#define Y4_GPIO_NUM  19
#define Y5_GPIO_NUM  21
#define Y6_GPIO_NUM  36
#define Y7_GPIO_NUM  39
#define Y8_GPIO_NUM  34
#define Y9_GPIO_NUM  35
#define XCLK_GPIO_NUM  0
#define PCLK_GPIO_NUM  22
#define VSYNC_GPIO_NUM  25
#define HREF_GPIO_NUM  23
#define SIOD_GPIO_NUM  26
#define SIOC_GPIO_NUM  27
#define PWDN_GPIO_NUM  32
#define RESET_GPIO_NUM  -1
#define LEDC_CHANNEL_0  LEDC_CHANNEL_0
#define LEDC_TIMER_0    LEDC_TIMER_0
